# Generated by Django 4.1.3 on 2022-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.CharField(db_index=True, max_length=355),
        ),
    ]
